language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
    - php: 7.1

before_script:
  - composer self-update
  - composer install

script:
  - ./vendor/bin/phpunit --coverage-text
